server:
  port: 8888
eureka:
  server:
    enableSelfPreservation: false
#    responseCacheUpdateInvervalMs: 3000
#    eviction-interval-timer-in-ms: 3000
#当前服务的local
  instance:
    hostname: localhost
  client:
  #registerWithEureka: false 和 fetchRegistry: false 表示当前服务是一个注册中心
    registerWithEureka: false
    fetchRegistry: false
    #配置注册中心的地址为当前服务的localhost、port加后缀名称
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
